services:
  db:
    container_name: postgres
    image: postgres:alpine
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - PGDATA=var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  postgres-it:
    container_name: postgres-it
    image: postgres:alpine
    ports:
      - "5332:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - PGDATA=var/lib/postgresql/data
    command: [ "postgres", "-c", "log_statement=all" ]
    networks:
      - postgres
    restart: unless-stopped
    depends_on:
      - db

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin4/storage
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
    depends_on:
      - db

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: