### Add Cinema Hall
POST http://localhost:8080/api/cinema_halls
Accept: application/json
Content-Type: application/json

{
  "id": null,
  "name": "Hall D",
  "capacity": 100
}

### Get All Cinema Halls
GET http://localhost:8080/api/cinema_halls
Accept: application/json
Content-Type: application/json

### Get Cinema Hall by ID
GET http://localhost:8080/api/cinema_halls/2
Accept: application/json
Content-Type: application/json

### Update Cinema Hall
PUT http://localhost:8080/api/cinema_halls/1
Accept: application/json
Content-Type: application/json

{
  "id": 4,
  "name": "Hall D",
  "capacity": 50
}

### Delete Cinema Hall
DELETE http://localhost:8080/api/cinema_halls/1
Accept: application/json
Content-Type: application/json