### Add Film
POST http://localhost:8080/api/film_shows
Accept: application/json
Content-Type: application/json

{
  "id": null,
  "filmId": 1,
  "cinemaHallId": 1,
  "startTime": "2024-07-21T10:00:00"
}

### Get All Films
GET http://localhost:8080/api/film_shows
Accept: application/json
Content-Type: application/json

### Get Film by ID
GET http://localhost:8080/api/film_shows/2
Accept: application/json
Content-Type: application/json

### Update Film
PUT http://localhost:8080/api/film_shows/1
Accept: application/json
Content-Type: application/json

{
  "id": 1,
  "filmId": 1,
  "cinemaHallId": 1,
  "startTime": "2024-07-21T22:00:00"
}

### Delete Film
DELETE http://localhost:8080/api/film_shows/1
Accept: application/json
Content-Type: application/json