### login admin
POST http://localhost:8080/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "admin@gmail.com",
  "password": "password"
}

> {%
    client.global.set("auth_token", "Bearer " + response.body.token);
%}

### login vip
POST http://localhost:8080/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "vip@gmail.com",
  "password": "password"
}

> {%
    client.global.set("auth_token", "Bearer " + response.body.token);
%}

### login user
POST http://localhost:8080/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "user@gmail.com",
  "password": "password"
}

> {%
    client.global.set("auth_token", "Bearer " + response.body.token);
%}

### get filmShow by id
GET http://localhost:8080/api/v1/filmshows/SHOW-2
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}


#### delete filmShow
DELETE http://localhost:8080/api/v1/filmshows/SHOW-1
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

### get all filmShows
GET http://localhost:8080/api/v1/filmshows
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

### get all filmShows
GET http://localhost:8080/api/v1/filmshows?page=0&size=3
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

### book seats
POST http://localhost:8080/api/v1/filmshows/SHOW-2/book
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

{
  "seatsIdentifiers": ["A1","A2"]
}

### book seats on behalf of the user
POST http://localhost:8080/api/v1/filmshows/SHOW-2/book
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

{
  "seatsIdentifiers": ["A1", "A2", "A3"],
  "userId": 3
}

### release seats
POST http://localhost:8080/api/v1/filmshows/SHOW-2/release
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

{
  "seatsIdentifiers": ["A1","A2"]
}

### create filmShow
POST http://localhost:8080/api/v1/filmshows
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

{
  "filmShowNumber": "FS3",
  "cinemaHallId": 1,
  "filmId": 1,
  "filmShowDateTime": "2024-08-12T17:15:00"
}


### Select Seats
POST http://localhost:8080/api/v1/filmshows/SHOW-2/book
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

{
  "seatsIdentifiers": ["A1","A2"]
}

### Create Order
POST http://localhost:8080/api/v1/filmshows/SHOW-2/order
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

### Initiate Payment
POST http://localhost:8080/api/v1/order/ORDER-1/process-payment
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

### Complete Payment
POST http://localhost:8080/api/v1/payment/PAYMENT-1/complete
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}
