### Add Film Show
POST http://localhost:8080/api/film_shows
Accept: application/json
Content-Type: application/json

{
  "id": null,
  "filmId": 3,
  "cinemaHallId": 1,
  "startTime": "2024-08-27T18:30:00"
}

### Get All Film Shows
GET http://localhost:8080/api/film_shows
Accept: application/json
Content-Type: application/json

### Get Film Show by ID
GET http://localhost:8080/api/film_shows/1
Accept: application/json
Content-Type: application/json

### Update Film Show
PUT http://localhost:8080/api/film_shows/1
Accept: application/json
Content-Type: application/json

{
  "id": 6,
  "filmId": 1,
  "cinemaHallId": 1,
  "startTime": "2024-07-21T22:00:00"
}

### Delete Film Show
DELETE http://localhost:8080/api/film_shows/1
Accept: application/json
Content-Type: application/json