### login admin
POST http://localhost:8080/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "admin@gmail.com",
  "password": "password"
}

> {% client.global.set("auth_token", "Bearer " + response.body.token); %}

### login user
POST http://localhost:8080/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "user@gmail.com",
  "password": "password"
}

> {% client.global.set("auth_token", "Bearer " + response.body.token); %}

### get order by number (only owner and admin)
GET http://localhost:8080/api/v1/order/ORDER-1
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

### logged user orders
GET http://localhost:8080/api/v1/order/my-orders?page=0&size=5
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

### get all orders (only admin)
GET http://localhost:8080/api/v1/order
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

### get paginated orders (only admin)
GET http://localhost:8080/api/v1/order?page=2&size=3
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}
