### Change seat status
POST http://localhost:8080/api/film-shows/seats/status
Accept: application/json
Content-Type: application/json

{
  "filmShowId": 1,
  "rowNumber": 1,
  "seatNumber": 1,
  "status": "OCCUPIED"
}
