### login admin
POST http://localhost:8080/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "admin@gmail.com",
  "password": "password"
}

> {% client.global.set("auth_token", "Bearer " + response.body.token); %}

### login user
POST http://localhost:8080/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "user@gmail.com",
  "password": "password"
}

> {% client.global.set("auth_token", "Bearer " + response.body.token); %}

### get ticket by number (only admin)
GET http://localhost:8080/api/v1/ticket/TICKET-1
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

### logged user tickets
GET http://localhost:8080/api/v1/ticket/my-tickets?page=0&size=5
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

### get all tickets (only admin)
GET http://localhost:8080/api/v1/ticket
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

### get paginated tickets (only admin)
GET http://localhost:8080/api/v1/ticket?page=2&size=3
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}
