### Generate ticket
POST http://localhost:8080/api/tickets
Accept: application/json
Content-Type: application/json

{
  "filmShowId": 5,
  "rowNumber": 1,
  "seatNumber": 1,
  "userId": 2
}

### Get all tickets
GET http://localhost:8080/api/tickets
Accept: application/json
Content-Type: application/json

### Invalidate ticket
POST http://localhost:8080/api/tickets/invalidate/1
Accept: application/json
Content-Type: application/json

### Use ticket
POST http://localhost:8080/api/tickets/use/1
Accept: application/json
Content-Type: application/json
